# Generated by Django 5.1.6 on 2025-09-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_baseachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('organizer_name', models.CharField(help_text='Internal Sub Organization within institution', max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('location_link', models.URLField(help_text='Event Venue')),
                ('created_timestamp', models.DateTimeField()),
                ('approval_timestamp', models.DateTimeField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='core.filelog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('support_docs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_docs', to='core.filelog')),
                ('tags', models.ManyToManyField(to='core.tags')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
