# Generated by Django 5.1.6 on 2025-09-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_competition_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
