# Generated by Django 5.1.6 on 2025-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_workshop_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_link', models.URLField()),
            ],
        ),
    ]
