# Generated by Django 5.1.6 on 2025-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognized_Student_Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_link', models.URLField()),
                ('global_chapter', models.BooleanField(help_text='Is it a National/Internation Student Chapter')),
                ('organization_strength', models.IntegerField(help_text='Approximate count of members')),
            ],
        ),
    ]
