# Generated by Django 5.1.6 on 2025-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filelog_created_by_alter_filelog_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='normalized_tag_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
