# Generated by Django 5.1.6 on 2025-09-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tags_normalized_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='normalized_tag_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
