# Generated by Django 5.1.6 on 2025-09-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tags_normalized_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.DateField()),
                ('end_on', models.DateField()),
                ('current', models.BooleanField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('current', True)), fields=('current',), name='unique_true_is_active')],
            },
        ),
    ]
