# Generated by Django 5.1.6 on 2025-09-19 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='association_name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='department',
            name='coordinatorname',
        ),
        migrations.AddField(
            model_name='department',
            name='HoD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
