# Generated by Django 5.1.6 on 2025-09-20 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_department_association_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='HoD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
