# Generated by Django 5.1.6 on 2025-09-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_staff_designation_alter_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='staff_designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.staff_designation'),
        ),
    ]
