# Generated by Django 5.1.6 on 2025-09-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_siteuser_staff_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='collegemail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
