# Generated by Django 5.1.6 on 2025-09-23 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('core', '0005_remove_workshop_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain'),
        ),
        migrations.CreateModel(
            name='Course_Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_timestamp', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('location_link', models.URLField(help_text='Event Venue Link')),
                ('verification_url', models.CharField(blank=True, help_text='Certificate Verification URL or Code(if applicable)', max_length=150, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approver', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_certificate', to='core.filelog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain')),
                ('support_docs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_support_docs', to='core.filelog')),
                ('tags', models.ManyToManyField(to='core.tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
