# Generated by Django 5.1.6 on 2025-09-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_competition_domain_workshop_domain_course_completion'),
        ('core', '0006_course_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_completion',
            name='course_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course_provider'),
        ),
    ]
