# Generated by Django 5.1.6 on 2025-09-23 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_course_completion_course_provider'),
        ('core', '0006_course_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_completion',
            name='course_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.course_provider'),
            preserve_default=False,
        ),
    ]
