# Generated by Django 5.1.6 on 2025-09-23 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_course_completion_course_provider'),
        ('core', '0006_course_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_timestamp', models.DateTimeField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=300)),
                ('organizer_name', models.CharField(blank=True, help_text='Internal Sub Organization within institution', max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('location_link', models.URLField(help_text='Event Venue Link')),
                ('github_link', models.URLField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approver', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_certificate', to='core.filelog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain')),
                ('support_docs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_support_docs', to='core.filelog')),
                ('tags', models.ManyToManyField(to='core.tags')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
