# Generated by Django 5.1.6 on 2025-09-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_preplacement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preplacement',
            old_name='institution',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='preplacement',
            name='organizer_name',
        ),
    ]
