# Generated by Django 5.1.6 on 2025-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_rename_institution_preplacement_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preplacement',
            name='role',
            field=models.CharField(default='', help_text='Describe your Role', max_length=100),
            preserve_default=False,
        ),
    ]
