# Generated by Django 5.1.6 on 2025-09-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_remove_preplacement_team_project'),
        ('core', '0007_recognized_student_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('approval_timestamp', models.DateTimeField(blank=True)),
                ('from_date', models.DateField(help_text='Tenure of service')),
                ('to_date', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('recognized_student_chap', models.BooleanField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approver', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_certificate', to='core.filelog')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.domain')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.recognized_student_body')),
                ('support_docs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_support_docs', to='core.filelog')),
                ('tags', models.ManyToManyField(to='core.tags')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
