# Generated by Django 5.1.6 on 2025-09-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_studentbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Service',
            fields=[
                ('studentbody_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.studentbody')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('activity.studentbody',),
        ),
    ]
