# Generated by Django 5.1.6 on 2025-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_social_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='filename', max_length=100)),
            ],
        ),
    ]
