# Generated by Django 5.1.6 on 2025-09-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activitymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_Service',
        ),
    ]
