# Generated by Django 5.1.6 on 2025-09-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_delete_social_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_link', models.URLField()),
                ('tenure_from', models.DateField(help_text='Tenure of service')),
                ('tenure_to', models.DateField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
