# Generated by Django 5.1.6 on 2025-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_social_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymanager',
            name='additional_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
