# Generated by Django 5.1.6 on 2025-09-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_competition_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='studentbody',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='studentbody',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='certificate',
            field=models.FileField(null=True, upload_to='student_certificates/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='support_docs',
            field=models.FileField(null=True, upload_to='support_docs/'),
        ),
    ]
