# Generated by Django 5.1.6 on 2025-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_alter_competition_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='course_completion',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='preplacement',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='studentbody',
            name='support_docs',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='support_docs',
        ),
        migrations.AddField(
            model_name='competition',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='competition',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='competition',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
        migrations.AddField(
            model_name='course_completion',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='course_completion',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='course_completion',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
        migrations.AddField(
            model_name='preplacement',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='preplacement',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='preplacement',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='project',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='project',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
        migrations.AddField(
            model_name='studentbody',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='studentbody',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='studentbody',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='brochures',
            field=models.FileField(null=True, upload_to='event_brochures/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='event_id',
            field=models.FileField(null=True, upload_to='event_id_photos'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='participation_photos',
            field=models.FileField(null=True, upload_to='participation_photos/'),
        ),
    ]
