# Generated by Django 5.1.6 on 2025-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_remove_competition_support_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentbody',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
