# Generated by Django 5.1.6 on 2025-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_alter_competition_created_by_and_more'),
        ('core', '0012_alter_tags_normalized_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_completion',
            name='brochures',
        ),
        migrations.RemoveField(
            model_name='course_completion',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='course_completion',
            name='participation_photos',
        ),
        migrations.AlterField(
            model_name='competition',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
        migrations.AlterField(
            model_name='studentbody',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tags'),
        ),
    ]
