# Generated by Django 5.1.6 on 2025-09-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0021_remove_course_completion_brochures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_completion',
            name='event_level',
        ),
    ]
