# Generated by Django 5.1.6 on 2025-09-26 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0022_remove_course_completion_event_level'),
        ('core', '0012_alter_tags_normalized_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentbody',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.domain'),
            preserve_default=False,
        ),
    ]
