# Generated by Django 5.1.6 on 2025-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_alter_competition_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='institution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course_completion',
            name='institution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='institution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
