# Generated by Django 5.1.6 on 2025-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_alter_competition_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_completion',
            name='verification_url',
            field=models.CharField(blank=True, help_text='Certificate Verification URL or Code(if available)', max_length=150, null=True),
        ),
    ]
