# Generated by Django 5.1.6 on 2025-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_alter_course_completion_verification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preplacement',
            name='brochures',
        ),
        migrations.RemoveField(
            model_name='preplacement',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='preplacement',
            name='participation_photos',
        ),
        migrations.AlterField(
            model_name='preplacement',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
