# Generated by Django 5.1.6 on 2025-09-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_remove_preplacement_brochures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preplacement',
            name='ppo_type',
            field=models.CharField(choices=[('INTERNSHIP', 'Internship'), ('APPRENTICESHIP', 'Apprenticeship'), ('FREELANCING', 'Freelancing')], default='Internship', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='mode_of_work',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
