# Generated by Django 5.1.6 on 2025-09-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_preplacement_ppo_type_workshop_mode_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preplacement',
            name='title',
        ),
    ]
