# Generated by Django 5.1.6 on 2025-09-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_remove_preplacement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware')], default='Hardware', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prototype_video',
            field=models.FileField(upload_to='project_videos/'),
        ),
    ]
