# Generated by Django 5.1.6 on 2025-09-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_project_project_type_alter_project_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='brochures',
        ),
        migrations.RemoveField(
            model_name='project',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='participation_photos',
        ),
    ]
