name: Deploy CPSAM

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:   # Optional: allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no phariprasath2006@34.47.162.19 << 'EOF'
            set -e
            cd /opt/smartathon
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            python manage.py migrate
            python manage.py test
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
