name: Deploy CPSAM to GCP VM

on:
  push:
    branches:
      - master  # Deploy only on master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.131.216.192 >> ~/.ssh/known_hosts

      # Step 3: Deploy to VM
      - name: Deploy to VM
        run: |
          ssh phariprasath2006@34.131.216.192 << 'EOF'
            # Navigate to project
            cd ~/CPSAM

            # Pull latest changes
            git fetch origin
            git reset --hard origin/master

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Apply database migrations
            python manage.py migrate --noinput

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart Gunicorn systemd service
            sudo systemctl restart gunicorn

            # Reload Nginx to ensure changes take effect
            sudo systemctl reload nginx
          EOF
