name: Deploy CPSAM to GCP VM

on:
  push:
    branches:
      - master  # Trigger only on master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.131.216.192 >> ~/.ssh/known_hosts

      # Step 3: Deploy to VM
      - name: Deploy to VM
        run: |
          ssh phariprasath2006@34.131.216.192 << 'EOF'
            cd /opt/CPSAM
            git config --global --add safe.directory /opt/CPSAM
            git pull origin master

            source venv/bin/activate
            pip install -r requirements.txt

            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            sudo kill -SIGUSR2 $(ps aux | pgrep gunicorn -o)
            gunicorn cpsam.wsgi worker=3 --daemon
          EOF

